//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murugi_25July.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string Location1 { get; set; }
        public string Location_ID { get; set; }
    }
}
